name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/setup-pages@v3

    - name: Deploy
      run: |
        mkdir output
        echo "Hello, GitHub Pages!" > output/index.html
