---
name: DevOps CI Workflow - Python
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
    # Etapa para fazer o checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

        #verificar se os arquivos estão no diretório
      - name: Verify requirements file
        run: ls -la

        #etapa para instalar dependÊncias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        #testar a qualidade do código Flake8 
      - name: Lint with flake8
        run: >
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Rodar testes automatizados com pytest
      - name: Run tests
        run: |
          pytest

        
